INSERT INTO blacklist VALUES(1,15);
INSERT INTO blacklist VALUES(4,1);
INSERT INTO blacklist VALUES(4,15);
INSERT INTO blacklist VALUES(6,15);
INSERT INTO blacklist VALUES(8,15);
INSERT INTO blacklist VALUES(8,1);
INSERT INTO blacklist VALUES(11,15);
INSERT INTO blacklist VALUES(14,15);